# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fb_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
